### ISSUE TITLE
Pairdrop has reset all my windows file associations?

### ISSUE THREAD

**Issue by mundodisco8** [ccarraher/pairdrop#1]
Hi,

I "installed" Pairdrop in my Windows computer, but now every time I open a file, Pairdrop wants to be the default app to open that file type, and that is quite annoying.

Can you review that?

I managed to reproduce in a clean Windows Sandbox. See attached gif

![Pairdrop_Small](https://user-images.githubusercontent.com/8402707/216025443-c54f862d-25e6-4336-9e8a-2e36fac981b6.gif)

1. Create a text file, for example.
2. Double click to confirm it's open with its default app, in this case notepad
3. Install Pairdrop
4. Open the text file again, a dialog appears suggesting Pairdrop as a potential default opener for text files.

**Comment by mundodisco8** [comment]
I opened the file associations setting in Windows. Pairdrop has associated with `.*`. 

![image](https://user-images.githubusercontent.com/8402707/216027446-2d7277e6-186f-4132-852a-d853f478fcc9.png)

I removed it from the registry, but I did a search for its key (Chrome.2803962851) and it appears hundreds of times for different, odd, extensions, I can't remove them by hand

![image](https://user-images.githubusercontent.com/8402707/216027620-6ac1c57e-c2e2-44a3-aac6-737b3f996437.png)

I uninstalled the app, and the issue disappears, but the registry entries remain.

**Comment by ccarraher** [comment]
Hey man sorry I can’t help you with this. I think you may be looking for: https://github.com/schlagmichdoch/PairDrop
I had the domain pairdrop.xyz back in the summer of 2020, which was a different app. Similar premise but mine was not nearly as mature.

**Comment by mundodisco8** [comment]
haha, oh my! sorry for the mistake.
